### ISSUE TITLE
What scope is necessary for the GitHub PAT in the learning labs?

### ISSUE THREAD

**Issue by boydj** [boozallen/sdp-docs#16]

**Comment by steven-terrana** [comment]
If you intend to create public repositories then your PAT is merely acting to authenticate to GitHub in order to avoid rate limiting and no scopes need be selected. 

If your repositories will be private i believe you'll need to add the `repo` scope to the token.

**Comment by steven-terrana** [comment]
Please feel free to open a PR updating the labs with this information! 

If interested, refer to [Contribute to the Documentation](https://boozallen.github.io/sdp-docs/overview/1/contribute-to-docs.html)!
