### ISSUE TITLE
Typo on lifecycle hook page

### ISSUE THREAD

**Issue by maximmold** [boozallen/sdp-docs#26]
![image](https://user-images.githubusercontent.com/348518/91565211-d8d76f00-e90f-11ea-9923-89f5f72aea57.png)

"thesesteps"

https://boozallen.github.io/sdp-docs/learning-labs/1/jte-advanced-features/3-pipeline-lifecycle-hooks.html

**Comment by cokieffebah** [comment]
Hi Maxim, 
While we appreciate you finding these issues, you can also submit a pull request with the corrections in these cases of simple misspellings and whatnot.
